apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/synbat-d/dispatcher-service/k8s?ref=f0894204c7e7eea8c26408f5f138674180d3e600

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: dispatcher-config

images:
- name: dispatcher-service
  newName: ghcr.io/synbat-d/dispatcher-service
  newTag: f0894204c7e7eea8c26408f5f138674180d3e600

replicas:
- count: 1
  name: dispatcher-service
