apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: config-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888 # Порт внутри контейнера (из твоего application.yml)
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "10"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  type: ClusterIP
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 80         # "Входная дверь" для других подов (как в книге)
      targetPort: 8888 # Куда перенаправлять трафик внутри пода