apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/synbat-d/catalog-service/k8s?ref=b96366d86af0a6db8b7a4e0f7908f86e95d76ec4
patchesStrategicMerge:
- patch-env.yml
- patch-volumes.yml
- patch-resources.yml
configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config
images:
- name: catalog-service
  newName: ghcr.io/synbat-d/catalog-service
  newTag: b96366d86af0a6db8b7a4e0f7908f86e95d76ec4

replicas:
  - count: 2
    name: catalog-service
