apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/synbat-d/order-service/k8s?ref=f98935cb2f8b8671e614b9dd062ae75332a976e5main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
- name: order-service
  newName: ghcr.io/synbat-d/order-service
  newTag: f98935cb2f8b8671e614b9dd062ae75332a976e5

replicas:
- count: 1
  name: order-service
