apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/synbat-d/edge-service/k8s?ref=74529e30a70289e7ef3e92981874d23852e95e33

patchesStrategicMerge:
- patch-env.yml
- patch-ingress.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-config

images:
- name: edge-service
  newName: ghcr.io/synbat-d/edge-service
  newTag: 74529e30a70289e7ef3e92981874d23852e95e33

replicas:
- count: 1
  name: edge-service
